### ISSUE TITLE
Create Markdown Textbox

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/BlockOverflow_frontend#11]
Create a textbox which supports markdown styling so users can type and view answers and doubts with it.

## Subtasks

- [x] Create a preview button to switch between markdown writing textbox to viewing textbox.
- [x] Fix Styling of doubts description form.
- [x] Add markdown writing textarea and preview area for doubts description.
- [x] Fix doubts form styling.
- [x] Allow the viewing of doubts on the site with markdown stylings.
